#
#     ____  _____ _     _     ____ _   _ ___
#    / ___|| ____| |   | |   / ___| | | |_ _|
#    \___ \|  _| | |   | |  | |  _| | | || |
#     ___) | |___| |___| |__| |_| | |_| || |
#    |____/|_____|_____|_____\____|\___/|___|
#           ( By Mackenzie Molloy )

# Support Discord | https://mackenziemolloy.net/discord

#
# Permissions:
#   - sellgui.use | Access to /sellgui (opens the sellgui)
#   - sellgui.reload | Access to /sellgui reload (reloads configuration)
#   - sellgui.debug | Access to /sellgui dump (dumps server information to a paste)
#

options:
  #
  # 0 - None
  # 1 - Hover message (Adds "receipt_text" to the end of the message)
  #
  receipt_type: 1
  sell_titles: true

  # Date format of transactions logging (http://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html)
  date_format: "yyyy/MM/dd HH:mm:ss"

  #
  # Whether prices should be rounded to 2 decimal places, or not.
  # This also formats prices with comma separation. IE: 1800 -> 1,800
  #

  rounded_pricing: false

  #
  # Whether trailing zero decimals should be removed (28.0, 28.00, etc --> 28)
  #

  remove_trailing_zeros: false

  #
  # Should units be abbreviated? eg: 1,259 -> 1.25k
  # Requires "rounded_pricing" to be false
  #

  abbreviate_numbers: false

  #
  # Sounds that are played during certain events
  #

  sounds:
    enabled: true
    error_notification: true # Whether there should be a console output notifying you that a sound is invalid
    pitch: 1
    volume: 1
    events:
      # If you don't want a certain event to have a sound, just set to an invalid value
      # NOTE: THESE DEFAULT VALUES ARE FOR 1.13+ AND MUST USE _ (underscore) INSTEAD OF . (dot)
      open: BLOCK_CHEST_OPEN
      success: ENTITY_VILLAGER_CELEBRATE
      failed: ENTITY_VILLAGER_HURT

  #
  # Action Bar Messages only work on versions 1.9+
  #
  action_bar_msgs: true

  #
  # Only relevent in versions prior to 1.13, basically do you want trialing ":(NUMBER)" on item lists (IE: "STONE:2")
  #

  show_item_damage: true

  #
  # How many rows the GUI will have
  # Min: 1 - Max: 6
  #
  rows: 6

  #
  # Similar to the SGP Item format: (EXAMPLE)
  # 1:
  #   type: dummy <--- Not required, but may become applicable in future updates I make
  #   item:
  #     material: STONE
  #     damage: 1 <--- Only use if you're running 1.12 or below
  #     quantity: 1
  #     name: "&7Cool name"
  #     lore:
  #       - "&7Lore Line 1"
  #       - "&9Lore line 2"
  #       ...and so on
  #     customModelData: 1
  #   commandsOnClick: (or commandsOnClickConsole)
  #     - "say %PLAYER%"
  #   slot: 1
  #

  decorations: []




messages:
  no_permission: "&cYou do not have permission"
  sellgui_title: "&0Sell GUI"
  reloaded_config: "&c[SellGUI] Reloaded configuration files."
  no_items_sold: "&aShop > &fYou didn't have anything sellable."
  no_items_in_gui: "&aShop > &fYou didn't place any items in the GUI."
  #
  # {list} - returns a list of sold items
  # {earning} - returns the total amount made
  # {amount} - returns amount of items sold
  #
  items_sold: "&aShop > &fYou sold &a{list}&f for &a{earning}&f."
  receipt_text: "&7(RECEIPT)"
  receipt_title: "&f&nReceipt for sell\n\n"
  #
  # {amount} - returns amount of item
  # {item} - returns item name
  # {price} - returns the selling price of the item
  #
  receipt_item_layout: "&a{amount} x {item} &ffor &a{price}"
  #
  # {amount} - returns amount of items sold
  # {earning} - returns the total amount made
  #
  sell_title: "&a&l+{earning}"
  sell_subtitle: "&7You sold &a&n{amount}&7 items in this batch"
  gamemode_not_allowed: "&aShop > &fYou are not allowed to use the Sell GUI in &a{gamemode} mode&f."
  inventory_full: "&aShop > &fYour inventory is currently full, so excess items have been dropped on the ground."
  #
  # {amount} - returns amount of items sold
  # {earning} - returns the total amount made
  #
  action_bar_items_sold: "&aShop > &fYou sold &a{amount} &fitems in this batch."
