#
#     ____  _____ _     _     ____ _   _ ___
#    / ___|| ____| |   | |   / ___| | | |_ _|
#    \___ \|  _| | |   | |  | |  _| | | || |
#     ___) | |___| |___| |__| |_| | |_| || |
#    |____/|_____|_____|_____\____|\___/|___|
#           ( By Mackenzie Molloy )

# Support Discord | https://discord.gg/qrmJXAD

#
# Permissions:
#   - sellgui.use | Access to /sellgui (opens the sellgui)
#   - sellgui.reload | Access to /sellgui reload (reloads configuration)
#   - sellgui.debug | Access to /sellgui dump (dumps server information to a paste)
#

options:
  #
  # 0 - None
  # 1 - Hover message (Adds "receipt_text" to the end of the message)
  #
  receipt_type: 1
  sell_titles: true
  #
  # Action Bar Messages only work on versions 1.9+
  #
  action_bar_msgs: true

  #
  # Only relevent in versions prior to 1.13, basically do you want trialing ":(NUMBER)" on item lists (IE: "STONE:2")
  #

  show_item_damage: true

  #
  # How many rows the GUI will have
  # Min: 1 - Max: 6
  #
  rows: 6

  #
  # Similar to the SGP Item format: (EXAMPLE)
  # 1:
  #   item:
  #     material: STONE
  #     damage: 1 <--- Only use if you're running 1.12 or below
  #     quantity: 1
  #     name: "&7Cool name"
  #     lore:
  #       - "&7Lore Line 1"
  #       - "&9Lore line 2"
  #       ...and so on
  #   slot: 1
  #

  decorations: []




messages:
  no_permission: "&cYou do not have permission"
  sellgui_title: "&0Sell GUI"
  reloaded_config: "&c[SellGUI] Reloaded configuration files."
  no_items_sold: "&aShop > &fYou didn't have anything sellable."
  #
  # {list} - returns a list of sold items
  # {earning} - returns the total amount made
  # {amount} - returns amount of items sold
  #
  items_sold: "&aShop > &fYou sold &a{list}&f for &a{earning}&f."
  receipt_text: "&7(RECEIPT)"
  receipt_title: "&f&nReceipt for sell\n\n"
  #
  # {amount} - returns amount of item
  # {item} - returns item name
  # {price} - returns the selling price of the item
  #
  receipt_item_layout: "&a{amount} x {item} &ffor &a{price}"
  #
  # {amount} - returns amount of items sold
  # {earning} - returns the total amount made
  #
  sell_title: "&a&l+{earning}"
  sell_subtitle: "&7You sold &a&n{amount}&7 items in this batch"
  gamemode_not_allowed: "&aShop > &fYou are not allowed to use the Sell GUI in &a{gamemode} mode&f."
  inventory_full: "&aShop > &fYour inventory is currently full, so excess items have been dropped on the ground."
  #
  # {amount} - returns amount of items sold
  # {earning} - returns the total amount made
  #
  action_bar_items_sold: "&aShop > &fYou sold &a{amount} &fitems in this batch."
